linters:
  ErbSafety:
    enabled: false

  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml

      Layout/ArgumentAlignment:
        Enabled: false
      Layout/FirstHashElementIndentation:
        Enabled: false
      Layout/HashAlignment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false

      Lint/UselessAssignment:
        Enabled: false

      Style/TrailingCommaInHashLiteral:
        Enabled: false

  NoJavascriptTagHelper:
    enabled: false
