linters:
  ErbSafety:
    enabled: false

  Rubocop:
    enabled: true
    rubocop_config:
      Layout/InitialIndentation:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/SpaceInsideHashLiteralBraces:
        EnforcedStyle: no_space
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false

      Lint/UselessAssignment:
        Enabled: false

      Style/FormatString:
        EnforcedStyle: percent
      Style/FormatStringToken:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Style/IfUnlessModifier:
        Enabled: false
      Style/TrailingCommaInArrayLiteral:
        EnforcedStyleForMultiline: comma

  NoJavascriptTagHelper:
    enabled: false
