extends:
  - stylelint-config-twbs-bootstrap

plugins:
  - stylelint-order

ignoreFiles:
  - vendor/**/*.css
  - vendor/**/*.scss

rules:
  order/properties-alphabetical-order: true
  order/properties-order: null
  selector-max-class: 8
  selector-max-compound-selectors: 8
  selector-max-id: null
  selector-no-qualifying-type: null
  stylistic/string-quotes: single
  stylistic/value-list-comma-newline-after: always-multi-line
  stylistic/value-list-comma-space-after: always-single-line
