default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  checkout_timeout: 5
  connect_timeout: 2
  variables:
    statement_timeout: 10s
    lock_timeout: 10s

development:
  <<: *default
  database: pirep_development
  host: localhost

test:
  <<: *default
  database: pirep_test
  host: localhost

production:
  <<: *default
  database: pirep_production
  host: <%= ENV['DATABASE_ENDPOINT'] %>
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  port: 5432
  username: <%= ENV['DATABASE_USERNAME'] %>
